postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=blabla
    - POSTGRES_USER=deploy
    - POSTGRES_DB=test


backupdb:
  environment:
    POSTGRES_DB: test
    CRON_TIME: '* * * * *'
    INIT_BACKUP: 'true'
    POSTGRES_USER: deploy
    POSTGRES_PASSWORD: blabla
    MAX_BACKUPS: 4
  build: .
  links:
    - postgres:postgres
  volumes:
  - backuptest:/backup
